package com.bzs_cns_mon.pub_bzs_cns_all_bre_panelist_rule_publish;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class panelist_bus_dim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public panelist_bus_dim() {
    }




}